Nick Garcia and Valerie Jimenez

In [ ]:
#https://www.kaggle.com/datasets/ishank2005/nyc-housing-prices-csv

In [ ]:
#Imported all necessary libraries for this random forest dataset
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [ ]:
from google.colab import files #imported the dataset into the google colab notebook
uploaded=files.upload()
df=pd.read_csv('nyc_housing_base.csv')#This file consisted of house details in NYC
df.head()

Saving nyc_housing_base.csv to nyc_housing_base.csv

,borough_x,block,lot,sale_price,zip_code,borough_y,yearbuilt,lotarea,bldgarea,resarea,comarea,unitsres,unitstotal,numfloors,latitude,longitude,landuse,bldgclass,building_age
0,1,400,11,280000,10009.0,MN,1900.0,2404.0,6875.0,6875.0,0.0,18.0,18.0,5.0,40.724415,-73.983891,2.0,C6,125.0
1,1,402,36,2000000,10009.0,MN,1900.0,1919.0,7810.0,6810.0,1000.0,8.0,10.0,5.0,40.724975,-73.981535,2.0,C4,125.0
2,1,402,60,3400000,10009.0,MN,1920.0,2150.0,6152.0,5352.0,800.0,8.0,9.0,5.0,40.725346,-73.983112,4.0,C7,105.0
3,1,404,42,4000000,10009.0,MN,1855.0,2369.0,6990.0,6990.0,0.0,10.0,10.0,5.0,40.727398,-73.980600,2.0,C4,170.0
4,1,372,55,655000,10009.0,MN,1920.0,5298.0,17990.0,17990.0,0.0,20.0,20.0,5.0,40.720621,-73.979534,2.0,C6,105.0

In [ ]:
df.isnull().sum() #Checking if null values are present in the data set

borough_x         0
block             0
lot               0
sale_price        0
zip_code         16
borough_y         0
yearbuilt         0
lotarea           0
bldgarea          0
resarea         188
comarea         188
unitsres          0
unitstotal        0
numfloors        43
latitude          6
longitude         6
landuse           3
bldgclass         0
building_age      0
dtype: int64

In [ ]:
df= df.dropna(subset=['zip_code']) #Dropped the null values in this columns
df

,borough_x,block,lot,sale_price,zip_code,borough_y,yearbuilt,lotarea,bldgarea,resarea,comarea,unitsres,unitstotal,numfloors,latitude,longitude,landuse,bldgclass,building_age
0,1,400,11,280000,10009.0,MN,1900.0,2404.0,6875.0,6875.0,0.0,18.0,18.0,5.0,40.724415,-73.983891,2.0,C6,125.0
1,1,402,36,2000000,10009.0,MN,1900.0,1919.0,7810.0,6810.0,1000.0,8.0,10.0,5.0,40.724975,-73.981535,2.0,C4,125.0
2,1,402,60,3400000,10009.0,MN,1920.0,2150.0,6152.0,5352.0,800.0,8.0,9.0,5.0,40.725346,-73.983112,4.0,C7,105.0
3,1,404,42,4000000,10009.0,MN,1855.0,2369.0,6990.0,6990.0,0.0,10.0,10.0,5.0,40.727398,-73.980600,2.0,C4,170.0
4,1,372,55,655000,10009.0,MN,1920.0,5298.0,17990.0,17990.0,0.0,20.0,20.0,5.0,40.720621,-73.979534,2.0,C6,105.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34434,5,7316,4,850000,10309.0,SI,1996.0,3180.0,1300.0,1300.0,0.0,2.0,2.0,2.0,40.535457,-74.223370,1.0,B9,29.0
34435,5,7317,130,855000,10309.0,SI,1995.0,3700.0,2500.0,2500.0,0.0,2.0,2.0,3.0,40.535470,-74.222060,1.0,B9,30.0
34436,5,7359,3,1200000,10309.0,SI,2001.0,4359.0,2200.0,2200.0,0.0,2.0,2.0,2.0,40.531791,-74.222555,1.0,B2,24.0
34437,5,6998,6,800000,10309.0,QN,1950.0,2185.0,1458.0,1458.0,0.0,1.0,1.0,2.0,40.726143,-73.800272,1.0,A5,75.0
34438,5,7267,81,999999,10309.0,SI,1999.0,6135.0,3750.0,0.0,3750.0,0.0,3.0,2.0,40.537937,-74.217960,5.0,O7,26.0

In [ ]:
# The rest of the columns will have all of the null values dropped

In [ ]:
df= df.dropna(subset=['resarea'])

In [ ]:
df= df.dropna(subset=['comarea'])

In [ ]:
df= df.dropna(subset=['numfloors'])

In [ ]:
df= df.dropna(subset=['landuse'])

In [ ]:
df= df.dropna(subset=['latitude'])

In [ ]:
df.isnull().sum() #Double checking to see if the null values have been dropped.

borough_x       0
block           0
lot             0
sale_price      0
zip_code        0
borough_y       0
yearbuilt       0
lotarea         0
bldgarea        0
resarea         0
comarea         0
unitsres        0
unitstotal      0
numfloors       0
latitude        0
longitude       0
landuse         0
bldgclass       0
building_age    0
dtype: int64

In [ ]:
df.drop('bldgclass', axis=1, inplace=True) #Dropped these columns as they are not needed for the decision tree
df.drop('borough_y', axis=1, inplace=True)

In [ ]:
df.drop('latitude', axis=1, inplace=True) #These were also dropped, we dropped them to get the best accuracy possible of the tree.
df.drop('longitude', axis=1, inplace=True)

In [ ]:
#Most of the columns were initially in float form, so we changed them into a integer form
#This will make it easier later when making our prediction
columns_to_convert = ['zip_code', 'yearbuilt', 'lotarea', 'bldgarea', 'resarea', 'comarea', 'unitsres', 'unitstotal', 'numfloors', 'landuse', 'building_age']
df[columns_to_convert] = df[columns_to_convert].astype(int)

In [ ]:
df

,borough_x,block,lot,sale_price,zip_code,yearbuilt,lotarea,bldgarea,resarea,comarea,unitsres,unitstotal,numfloors,landuse,building_age
0,1,400,11,280000,10009,1900,2404,6875,6875,0,18,18,5,2,125
1,1,402,36,2000000,10009,1900,1919,7810,6810,1000,8,10,5,2,125
2,1,402,60,3400000,10009,1920,2150,6152,5352,800,8,9,5,4,105
3,1,404,42,4000000,10009,1855,2369,6990,6990,0,10,10,5,2,170
4,1,372,55,655000,10009,1920,5298,17990,17990,0,20,20,5,2,105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34434,5,7316,4,850000,10309,1996,3180,1300,1300,0,2,2,2,1,29
34435,5,7317,130,855000,10309,1995,3700,2500,2500,0,2,2,3,1,30
34436,5,7359,3,1200000,10309,2001,4359,2200,2200,0,2,2,2,1,24
34437,5,6998,6,800000,10309,1950,2185,1458,1458,0,1,1,2,1,75
34438,5,7267,81,999999,10309,1999,6135,3750,0,3750,0,3,2,5,26

In [ ]:
#We are splitting the dataset, the X variables will determine the building age
#We made the building age the target variable
x_data=df[['borough_x', 'block', 'lot', 'sale_price', 'zip_code', 'yearbuilt', 'lotarea', 'bldgarea', 'resarea', 'comarea', 'unitsres', 'unitstotal', 'numfloors', 'landuse' ]]
y_data=df['building_age']

In [ ]:
#This will split the dataset inot a traning and test set
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=1)

In [ ]:
# This trains a single decision tree
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(x_train, y_train)

#This will calculate the accuracy with the dt_accuracy variable
dt_accuracy = dt_model.score(x_test, y_test)
#Prints the final accuracy %
print("Decision Tree Test Accuracy:", f"{dt_accuracy * 100:.2f}%")

Decision Tree Test Accuracy: 99.87%

In [ ]:
#This will train the random forest with a random feature
rf_model = RandomForestClassifier(n_estimators=14, max_features=2, random_state=42)

rf_model.fit(x_train, y_train)

#This will calculate the accuracy of the forest
#Instead with a rf_accuracy
rf_accuracy = rf_model.score(x_test, y_test)

#prints the final accuracy
print("RF Model Accuracy:", f"{rf_accuracy *100:.2f}", "%")

RF Model Accuracy: 72.07 %

In [ ]:
#This will train the random forest
#It prepares the dataset for a precision, recall, and f1 %
rf_model = RandomForestClassifier(n_estimators=14, max_features=2, random_state=42)

rf_model.fit(x_train, y_train)
#This will make the prediction of the testing set
y_pred_rf = rf_model.predict(x_test)

#Calculation the precision, recall, and the F1 score for the random forest
precision_rf = metrics.precision_score(y_test, y_pred_rf, average='weighted')
recall_rf = metrics.recall_score(y_test, y_pred_rf, average='weighted')


f1_rf = metrics.f1_score(y_test, y_pred_rf, average='weighted')
#Prints the final % for all three
print("RF Precision:", precision_rf)
print("RF Recall:", recall_rf)
print("RF F1-Score:", f1_rf)

RF Precision: 0.7807795315707768
RF Recall: 0.7859961993860547
RF F1-Score: 0.7772132801244578

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
#This will prepare a new entry and a prediction
def predict_houses():
    while True:
        try:
            borough_x = int(input("Enter the Borough Number: "))
            block = int(input("Enter the block number: "))
            lot = int(input("Enter the lot number: "))
            sale_price = int(input("Enter the sale price:  "))
            zip_code = int(input("Enter the zip code: "))
            yearbuilt = int(input("Enter the year built: "))
            lotarea = int(input("Enter the lot area number: "))
            bldgarea = int(input("Enter the building area number: "))
            resarea = int(input("Enter the res area number: "))
            comarea = int(input("Enter the com area number: "))
            unitsres = int(input("Enter the unitres number: "))
            unitstotal = int(input("Enter the total units: "))
            numfloors = int(input("Enter the number of floors: "))
            landuse = int(input("Enter the land use number: "))
#This will validate the values and make sure there aren't any negative values inputted
            if any(val < 0 for val in [borough_x, block, lot, sale_price, zip_code, yearbuilt, lotarea, bldgarea, resarea, comarea, unitsres, unitstotal, numfloors, landuse]):
                print("Error: Please enter a non-negative value for all feautures.")
                continue
#This will start the prediction of the "new" dataset that we have created
            new_house_data = pd.DataFrame([[borough_x, block, lot, sale_price, zip_code, yearbuilt, lotarea, bldgarea, resarea, comarea, unitsres, unitstotal, numfloors, landuse]],
                                          columns= ['borough_x', 'block', 'lot', 'sale_price', 'zip_code', 'yearbuilt', 'lotarea', 'bldgarea', 'resarea', 'comarea', 'unitsres', 'unitstotal', 'numfloors', 'landuse'])
            prediction = rf_model.predict(new_house_data)[0]
#This will determine if the house is under or over 100 years old
            if prediction > 100:
                #It will print a message for either outcome
                print("Prediction: The house is at least 100 years old ")
            else:
                print("Prediction: The house is less than 100 years old:")
#This gives the option to enter new data for a new outcome
            another_house = input("Enter data for another house? (yes/no): ")
            if another_house.lower() != 'yes':
                break
        except ValueError as e: #if there is a a error it will have you restart and enter the correct values
              print("Invalid input. Please enter a valid number.")
              print("Error:", e)

predict_houses() #This will start the prediction

Enter the Borough Number: 5
Enter the block number: 400
Enter the lot number: 42
Enter the sale price:  200000
Enter the zip code: 10009
Enter the year built: 1999
Enter the lot area number: 2404
Enter the building area number: 6875
Enter the res area number: 6875
Enter the com area number: 18
Enter the unitres number: 18
Enter the total units: 5
Enter the number of floors: 2
Enter the land use number: 2
Prediction: The house is less than 100 years old:
Enter data for another house? (yes/no): no

In [ ]:
#Shows the features/columns importance. This will display a table of both columns
feature_importances = pd.DataFrame({'feature': x_data.columns, 'importance': rf_model.feature_importances_})
feature_importances = feature_importances.sort_values('importance', ascending=False)
feature_importances

       feature  importance
5    yearbuilt    0.331356
1        block    0.086295
7     bldgarea    0.082595
6      lotarea    0.080810
8      resarea    0.076012
2          lot    0.071966
4     zip_code    0.067679
3   sale_price    0.063268
10    unitsres    0.031502
11  unitstotal    0.029369
12   numfloors    0.028627
0    borough_x    0.020160
9      comarea    0.018758
13     landuse    0.011602

My partner and I decided to use this NYC housing dataset for one of our random forests. We wanted to see the outcome of whether a house is over or less than 100 years old. This algorithm will create multiple decision trees where it creates different classes to determine a certain outcome. The random forest grabs "random" trees to test out the accuracy of variables we have chosen while including the outcome. These variable consisted of house stats, these stats include the lot number, zip_code, sale_price etc. We decided to choose the house age as the target outcome and we got a 99% accuracy of the trees that were randomly chosen. This means we have enough and accurate information to determine the age of the house. We also used a precision, recall, and f1 score which basically determines the accuracy and how true the data is to itself.

We used a prediction code for the user to manually inputt and determine if the house is 100 years old based on the stats given. At the very end we displayed a table that orders the importance of each stat. This shows how important the zip code or the lot number is when determining the age of the house. A good note for this algorithm is that randomly chooses the decision trees and leaves the rest. Which means whatever is not chosen, it will not be used to determine the accuracy of target outcome.